name: required-reviewers
description: Checks the required reviewers have approved a PR.
author: theoremlp
inputs:
  github-token:
    required: true
    description: A valid GitHub token
runs:
  using: "node16"
  main: "dist/main.js"
